### ISSUE TITLE
User password getting hashed more than once on pre save hook

### ISSUE THREAD

**Issue by PoorlyDefinedBehaviour** [CollabCodeTech/collabcodetraining-api-auth#32]
**Describe the bug**
User password is getting hashed every time the model is saved, because of pre save hook.
Hashing the hashed password can result in a lost account.

It's happening because there are no checks on User.pre("save") hook, even though there is only one route that triggers this operation at the moment, it's probable that there'll be more in the future.

**To Reproduce**

1. Copy paste the code
2. Make sure you have bcryptjs installed

```js
const bcrypt = require("bcryptjs");

async function main() {
  const password = "hello world!";

  const hashed_once = await bcrypt.hash(password, 10);
  const hashed_twice = await bcrypt.hash(hashed_once, 10);

  const equal_hashed_once = await bcrypt.compare(password, hashed_once);
  console.log("equal_hashed_once =>", equal_hashed_once); // true

  const equal_hashed_twice = await bcrypt.compare(password, hashed_twice);
  console.log("equal_hashed_twice =>", equal_hashed_twice); // false
}
main();
```

**Expected behavior**
User password should be hashed only once when it has been modified.

**Comment by masterl** [comment]
Are you going to send a PR for this or can I do it? @PoorlyDefinedBehaviour

**Comment by PoorlyDefinedBehaviour** [comment]
> Are you going to send a PR for this or can I do it? @PoorlyDefinedBehaviour

Go ahead. @masterl
